// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnewcokwwpaoiynjhgtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZXdjb2t3d3Bhb2l5bmpoZ3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDgzMTMsImV4cCI6MjA2NzMyNDMxM30.7AGKeA92OkpQBLqteynEuYJdQBZUsPxNjPYo6TY536g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});